apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets-operator
resources: 
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - external-secrets-operator-config.yaml
  - vault-cluster-secret-store.yaml
  - test-external-secret.yaml