apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
metadata:
  name: openshift-gitops-cluster
resources:
  #syncwave0
  - openshift-gitops-cluster.yaml
  - openshift-gitops-operator.yaml
  #syncwave1
  - openshift-nmstate.yaml
  - external-secrets-operator.yaml
  #syncwave2
  - openshift-storage.yaml
  #- cert-manager-operator.yaml
  #- openshift-cnv.yaml