apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - trusted-ca-config-map.yaml
  - cloudflare-api-token-external-secret.yaml
  - lets-encrypt-cluster-issuer.yaml
  - ingress-certificate.yaml
  - api-certificate.yaml
  - certificate-patch-job.yaml