apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization

resources:
  - namespace.yaml
  - operator-group.yaml
  - local-storage-operator-subscription.yaml
  #- odf-operator-subscription.yaml
  #- enable-odf-console-plugin-job.yaml
  #- label-node-job.yaml
  #- auto-discover-devices.yaml
  #- default-lvs.yaml
  #- ocsinit.yaml
  #- ocs-storagecluster.yaml